source "https://rubygems.org"

ruby "3.0.2"

gem "tzinfo-data", platforms: %i[ windows jruby ]


group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]
  gem 'faker'
end

gem "debug"

gem "ruby-openai"
#gem 'dotenv-rails', groups: [:development, :test]

gem "daru"


gem "matrix", "~> 0.4.2"

gem "pdf-reader"

gem "dotenv"


gem 'tokenizers'

gem "psych", "~> 3.0"
